/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rpc.thrift.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-11-25")
public class rpcResponse implements org.apache.thrift.TBase<rpcResponse, rpcResponse._Fields>, java.io.Serializable, Cloneable, Comparable<rpcResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("rpcResponse");

  private static final org.apache.thrift.protocol.TField REPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("reponse", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new rpcResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new rpcResponseTupleSchemeFactory());
  }

  public String reponse; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REPONSE((short)1, "reponse");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REPONSE
          return REPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REPONSE, new org.apache.thrift.meta_data.FieldMetaData("reponse", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(rpcResponse.class, metaDataMap);
  }

  public rpcResponse() {
  }

  public rpcResponse(
    String reponse)
  {
    this();
    this.reponse = reponse;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public rpcResponse(rpcResponse other) {
    if (other.isSetReponse()) {
      this.reponse = other.reponse;
    }
  }

  public rpcResponse deepCopy() {
    return new rpcResponse(this);
  }

  @Override
  public void clear() {
    this.reponse = null;
  }

  public String getReponse() {
    return this.reponse;
  }

  public rpcResponse setReponse(String reponse) {
    this.reponse = reponse;
    return this;
  }

  public void unsetReponse() {
    this.reponse = null;
  }

  /** Returns true if field reponse is set (has been assigned a value) and false otherwise */
  public boolean isSetReponse() {
    return this.reponse != null;
  }

  public void setReponseIsSet(boolean value) {
    if (!value) {
      this.reponse = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REPONSE:
      if (value == null) {
        unsetReponse();
      } else {
        setReponse((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REPONSE:
      return getReponse();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REPONSE:
      return isSetReponse();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof rpcResponse)
      return this.equals((rpcResponse)that);
    return false;
  }

  public boolean equals(rpcResponse that) {
    if (that == null)
      return false;

    boolean this_present_reponse = true && this.isSetReponse();
    boolean that_present_reponse = true && that.isSetReponse();
    if (this_present_reponse || that_present_reponse) {
      if (!(this_present_reponse && that_present_reponse))
        return false;
      if (!this.reponse.equals(that.reponse))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_reponse = true && (isSetReponse());
    list.add(present_reponse);
    if (present_reponse)
      list.add(reponse);

    return list.hashCode();
  }

  @Override
  public int compareTo(rpcResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReponse()).compareTo(other.isSetReponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reponse, other.reponse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("rpcResponse(");
    boolean first = true;

    sb.append("reponse:");
    if (this.reponse == null) {
      sb.append("null");
    } else {
      sb.append(this.reponse);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (reponse == null) {
      throw new TProtocolException("Required field 'reponse' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class rpcResponseStandardSchemeFactory implements SchemeFactory {
    public rpcResponseStandardScheme getScheme() {
      return new rpcResponseStandardScheme();
    }
  }

  private static class rpcResponseStandardScheme extends StandardScheme<rpcResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, rpcResponse struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reponse = iprot.readString();
              struct.setReponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, rpcResponse struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.reponse != null) {
        oprot.writeFieldBegin(REPONSE_FIELD_DESC);
        oprot.writeString(struct.reponse);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class rpcResponseTupleSchemeFactory implements SchemeFactory {
    public rpcResponseTupleScheme getScheme() {
      return new rpcResponseTupleScheme();
    }
  }

  private static class rpcResponseTupleScheme extends TupleScheme<rpcResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, rpcResponse struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.reponse);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, rpcResponse struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.reponse = iprot.readString();
      struct.setReponseIsSet(true);
    }
  }

}

